"""Markdown Exporter module for Outlier Engine reports."""

from outlier_engine.models import EngineReport


class MarkdownExporter:
    """Exporter responsible for rendering EngineReport as a Markdown document."""

    @staticmethod
    def export(report: EngineReport) -> str:
        """Export EngineReport to a Markdown formatted string."""
        lines = []
        lines.append("# Outlier Engine Execution Report")
        lines.append("")
        lines.append("## Execution Context")
        lines.append(f"- **Execution ID:** `{report.context.execution_id}`")
        lines.append(f"- **Timestamp:** {report.context.timestamp}")
        lines.append(f"- **Strict Numeric:** {report.context.strict_numeric}")
        lines.append(f"- **Inplace Processing:** {report.context.inplace}")
        lines.append(
            f"- **Total Outliers Detected:** {report.total_outliers_detected}")
        lines.append("")

        lines.append("## Dataset Metadata")
        lines.append(f"- **Total Rows:** {report.metadata.total_rows}")
        lines.append(f"- **Total Columns:** {report.metadata.total_columns}")
        lines.append(
            f"- **Processed Columns:** {', '.join(report.metadata.processed_columns) if report.metadata.processed_columns else 'None'}"
        )
        lines.append("")

        lines.append("## Column Summaries")
        if not report.column_summaries:
            lines.append("No columns were processed.")
        else:
            lines.append(
                "| Column | Method | Treatment | Outliers | Lower Bound | Upper Bound |")
            lines.append("| --- | --- | --- | --- | --- | --- |")
            for col, summary in report.column_summaries.items():
                lb = f"{summary.lower_bound:.2f}" if summary.lower_bound is not None else "N/A"
                ub = f"{summary.upper_bound:.2f}" if summary.upper_bound is not None else "N/A"
                lines.append(
                    f"| {summary.column_name} | {summary.detection_method} | {summary.treatment_action} | {summary.outliers_detected} | {lb} | {ub} |"
                )

        lines.append("")
        lines.append("---")
        lines.append("*Generated by Outlier Engine Reporting Module*")
        return "\n".join(lines)
